<<<<<<< HEAD
# Generated by Django 2.1 on 2018-10-01 16:43
=======
# Generated by Django 2.1.1 on 2018-09-30 14:06
>>>>>>> origin/CH

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('Tag', models.CharField(choices=[(0, 'WEB'), (1, 'PWN'), (2, 'Reverse'), (3, 'Crypto'), (4, 'MISC')], max_length=32)),
=======
                ('Tag', models.CharField(choices=[(0, 'WEB'), (1, 'PWN'), (2, 'Reverse'), (3, 'Crypto'), (4, 'MISC')], max_length=256)),
>>>>>>> origin/CH
                ('Name', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=256)),
                ('Link', models.CharField(max_length=256)),
                ('Score', models.IntegerField(default=200)),
                ('Flag', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('WhichQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('WhoSolve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
            ],
        ),
    ]
