# Generated by Django 2.1.2 on 2018-10-04 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apply_for',
            field=models.ManyToManyField(related_name='apply_for', to='user.Team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_for', to='user.Team'),
        ),
    ]
